services:
  app_proxy:
    environment:
      APP_HOST: kan_server_1
      APP_PORT: 3000
  server:
    image: ghcr.io/kanbn/kan:latest@sha256:8dc287ce63d2078b77d0b3f5560e3280c406fcbb77db84721dcfa6a8fa83d46f
    environment:
      NEXT_PUBLIC_BASE_URL: http://${DEVICE_DOMAIN_NAME}:8373
      BETTER_AUTH_SECRET: ${APP_SEED}
      POSTGRES_URL: 'postgresql://kanuser:kanpassword@kan_db_1:5432/kan?sslmode=disable'
      NEXT_PUBLIC_ALLOW_CREDENTIALS: "true"
    depends_on:
      - db
    restart: on-failure

  db:
    image: postgres:17.3@sha256:0321e2252ebfeecb8bc1a899755084d29bce872953e1a5a3e25ec0860b739098
    user: "1000:1000"
    environment:
      POSTGRES_DB: kan
      POSTGRES_USER: kanuser
      POSTGRES_PASSWORD: kanpassword
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data/db:/var/lib/postgresql/data
