services:
  app_proxy:
    environment:
      APP_HOST: flaresolverr_server_1
      APP_PORT: 8191

  server:
    image: ghcr.io/flaresolverr/flaresolverr:v3.4.2@sha256:42ffb1cc56088899e91a7382bc611b00fa7cbd016accfed12c0695275ca18451
    environment:
      LOG_LEVEL: info
    restart: on-failure